import itertools
from collections import defaultdict
from math import ceil
from typing import Generator, Container, Iterable

import Bio
import numpy as np
import nupack
import pandas as pd

from .create_same_tm_seq_library import get_unbound_fraction
from .seqgen import generate_unique_sequence
from .sequence_optimization_functions import compute_dGs
from ..structure_editor.dna_structure import rc


def check_seq_valid(seq: str, min_polybase:int=3, max_polybase=6) -> bool:
    """
    version of create_same_tm_seq_library.seq_check optimized by chatGPT
    i think it may be possible to further optimize but idk
    """
    for base in 'ATGC':
        if any(base * n in seq for n in range(max_polybase, min_polybase-1, -1)):
            return False

    # Check that all four bases are present
    if not all(b in seq for b in 'ATGC'):
        return False

    return True

def is_rc(name: str ) -> bool:
    """
    tests if the domain identifier identifies the reverse compliment of a different sequence
    """
    return name.startswith('-') or name.endswith("'")

def name_rc(name: str) -> str:
    """
    constructs an identifier (name) for the domain that is the reverse compliment of the name provided
    """
    if is_rc(name):
        if name.startswith('-'):
            return name[1:]
        else:
            return name[:-1]
    else:
        return name+"'"


class OrthogonalSequenceSetDesigner:
    """
    class to design sets of orthogoanl DNA sequences with varying lengths
    """
    # -------------------------------------- designer parameters ------------------------------------------------------
    # desired melting temperature. DO NOT ADJUST.
    temperature: float
    temperature_tolerance: float
    # melting temperature algorithm to use. options: 'both', 'biopy', 'nupack
    mt_algo: str
    # maximum allowed number of secondary structures
    filter_struct: int # todo: modify this for strands designed to form secondary structures
    # -------------------------------------- design requirements ------------------------------------------------
    # DNA sequences associated with domains. each domain is a sequence that does a something.
    # domains are identified by a string (can be a number string), sequences are written 5'->3'
    # domains beginning with "-" or ending with "'" are assumed to be reverse compliments
    domains: dict[str, str]
    # motif is set of desired sequences. each motif is a list of domain indicators written 5'->3'.
    # do NOT confuse motif and domain names, and avoid using the same name for a sequence and for a motif!
    motifs: dict[str, list[str]]
    # info on requested domains
    requested_domains: dict[str, tuple[int, int]]

    # ---------------------------------------- runtime variables ----------------------------------------------
    model: nupack.Model
    # sequences by length and GC count
    # seqs_by_len_gc: dict[tuple[int,int], set[str]]
    # sequence generators, generated by `generate_unique_sequence`
    seq_generators_by_len_gc: dict[tuple[int,int], Generator[str, None, None]]

    # ----------------- compute runtime vars. todo: spinoff to own class -----------------
    # number of distinct domains required for each (len, gc) pair
    __c_request_counts: dict[tuple[int, int], int]
    # map where keys are (len, gc) and values are sets of sequences with len and gc
    __c_candidates: dict[tuple[int, int], set[str]]

    def __init__(self, temperature: float, temperature_tolerance: float = 0.5, mt_algo: str = "biopy"):
        """
        constructor
        """
        self.temperature = temperature
        self.temperature_tolerance = temperature_tolerance
        self.domains = dict()
        self.motifs = dict()
        self.requested_domains = dict()
        if mt_algo not in ["biopy", "both", "nupack"]:
            raise Exception(f"Unknown melting temperature algorithm {self.mt_algo}")
        self.mt_algo = mt_algo
        # todo: make Na and Mg params?
        self.model = nupack.Model(material='dna',
                                  celsius=self.temperature,
                                  sodium=0.05, # in M
                                  magnesium=0.0125 # in M
                                  )
        self.seq_generators_by_len_gc = {}

    def request_motifs(self, motifs: dict[str, Iterable[str]]):
        """
        requests motifs. each motif is a list of domain identifier strings, orded 5' -> 3'
        """
        for motif_name, motif in motifs.items():
            if motif_name not in self.motifs:
                self.motifs[motif_name] = list(motif)

    def request_domains(self, domains: dict[str, tuple[int, int]]):
        """
        generates domains
        Parameters:
            domains: each item is (domain identifier, sequence length, gc count)
        """
        self.requested_domains.update(domains)

    def seqs_oxDNA(self):
        """
        returns a key->value dict of sequence names -> sequences, where sequences are written in oxDNA format
        note that this reverses the direction of the sequence because oxDNA sequences are written 3'->5' (UGH)
        but here i write them 5'->3' because that is the correct way to do it
        """
        return {
            key: sum(self.domains[key])[::-1] for key in self.domains
        }

    def check_request_valid(self):
        """
        checks if the request is valid
        """
        for motif_domains in self.motifs.values():
            for domain in motif_domains:
                if any([c!="_" for c in domain]):
                    found = False
                    # reverse compliments make this hard
                    # standardize search term to non-rc name
                    if domain.startswith("-"):
                        search_term = domain[1:]
                    elif domain.endswith("'"):
                        search_term = domain[:-1]
                    else:
                        search_term = domain

                    for d, _ in self.requested_domains.items():
                        found = search_term == d
                        if found:
                            break
                    if not found:
                        # todo: custom exception
                        raise Exception(f"{domain} (or its reverse compliment) is not in requested domain list")

    def compute(self, min_ddg: float, pool_size_relative: float=1.2):
        """
        massive function to execute computation
        we will probably need to expand search space at some point
        Parameters:
            min_ddg: minimum delta-delta-g for set of sequences we generate
            pool_size_relative: how many candidates to initially compute (after Tm screen but before ddG
                                screen) for each sequence requested
        """
        assert pool_size_relative > 1
        self.check_request_valid()

        # todo: allow for dynamically varying gc counts if we can't find a good Tm or good ddG
        worst_ddG = 0

        # these next two class members are temporary for use within this method and its submethods
        self.__c_request_counts = dict()
        # map where keys are (len, gc) and values are sets of sequences with len and gc
        self.__c_candidates  = dict()

        # count how many sequences we want to have for each (len, gc) when we're done
        for domain_name, (domain_len, domain_gc) in self.requested_domains.items():
            self.__c_candidates[(domain_len, domain_gc)] = set() # redundant declaration is ok
            self.__c_request_counts[(domain_len, domain_gc)] = self.__c_request_counts[(domain_len, domain_gc)] + 1 \
                if (domain_len, domain_gc) in self.__c_request_counts else 1


        print("Requesting " + ';'.join([f'{l}bp, {gc}GCs: {n} sequences'
                                      for (l, gc), n in self.__c_request_counts.items()]))
        # find candidate sequences
        # while our best set of domain sequences has a worse
        while worst_ddG < min_ddg:
            self.__try_find_sequence_set(pool_size_relative)

            # now that we have a set of candidates, the true nightmare begins
            # first thing we need to do here is find ddGs for strand pairs
            # FIRST first thing we need to do is start constructing sets of domain-candidate assignments

            # for each (dlen, dgc) specification

            # we want to check unique assignments of domains to sequences
            # the problem arises when we have multiple motifs that consist of only one domain (not counting spacers)
            # and that domain has the same (dlen, dgc) requirement
            # in this instance we will end up WILDLY overcomputing because
            # (for domains a and b and strands _a and _b) sequence a=seq1, b=seq2 is identical to b=seq1, a=seq2
            # so we should be looking for *combinations* not *permutations*
            # if we have for example 10 such identical sequences

            # the other problem is that no matter whether we're talking about combinations or permutations, the
            # number of possibilities involved rapidly becomes one of those numbers that you don't need to
            # state in detail because what matters is that it is Too Big

            # so what we need to do is randomly jump around domain-assignment space
            # until we've found a set of domain assignments that

            for domain_assignments in self.__iter_domain_assigments():
                dGs_output: pd.DataFrame = self.__find_strand_dgs(domain_assignments)

            # increase relative pool size.
            pool_size_relative *= 1.25 # increase pool size

    def __try_find_sequence_set(self, pool_size_relative: int):
        """
        finds a set of sequences from the given pool size
        when the function is done executing it should have
        """

        # count requests for relative pool size
        self.__c_request_counts = defaultdict(lambda: pool_size_relative)
        # request count for each (len, gc) pair should be the number of domains of that (len, gc) times the pool size
        for domain_name, (domain_len, domain_gc) in self.requested_domains.items():
            self.__c_request_counts[(domain_len, domain_gc)] = self.__c_request_counts[(domain_len, domain_gc)] + pool_size_relative

        self.__request_domain_seq_candidates(1) # request initial sequences, starting from the pool size (=1)
        # todo: may want to chunk this more optimally

        # while we haven't found enough candidates with correct Tm
        prescreen_pool_size_relative = 1
        while not self.__try_find_candidate_set(pool_size_relative):
            # request more candidates
            self.__request_domain_seq_candidates(pool_size_relative)
            pool_size_relative *= pool_size_relative # increase prescreen pool size
            # todo better exit condition for if we run out of possible sequences
        # if we are done then good!
        print(f"Identified {len(list(itertools.chain.from_iterable(self.__c_candidates.values())))} candidates for domain sequences")

    def __try_find_candidate_set(self, prescreen_pool_size_relative: float) -> bool:
        """
        attempts to find sets of candidate sequences for domains given the pool size
        Args:
            prescreen_pool_size_relative: the relative size of the pool of domain sequence candidates to generate before motif-wise screening
        """
        print(f"Attempting to find domain candidate sequences with relative pool size {prescreen_pool_size_relative}")
        # local set of candidates. keys are domain names, values are sets of candidate sequences
        candidates_by_name = dict()
        for domain_name, (dlen, dgc) in self.requested_domains.items():
            # we need to assign these seperately from `candidates` because self.generate_sequences isn't const
            candidates_by_name[domain_name] = self.__c_candidates[(dlen, dgc)]

        usable_domain_candidates: dict[str, set[str]] = {name: set() for name in candidates_by_name.keys()}
        # keep track of how many options we have for fulfilling each motif
        motif_fulfillment_options: dict[str, set[frozenset[tuple[str, str]]]] = dict()
        # iter motifs
        for mname, motif in self.motifs.items():
            motif_fulfillment_options[mname] = set()
            combinables = []
            for domain_name in motif:
                if "_" in domain_name:
                    continue
                elif is_rc(domain_name):
                    rc_name = name_rc(domain_name)
                    combinables.append(
                        {rc(seq) for seq in candidates_by_name[rc_name]}
                )
                else:
                    combinables.append(candidates_by_name[domain_name])

            # for each set of sequences that could make up this motif (poly-Ts explicitly)
            found_any_candidate_set = False
            for candidate_set in itertools.product(*combinables):
                seq: str = "".join(candidate_set)
                # if the domains - when joined have an unacceptable polynucleotide, exclude immediately
                if check_seq_valid(seq):
                    Tm = self.get_tm_seq(seq)
                    if Tm > self.temperature + self.temperature_tolerance or Tm < self.temperature - self.temperature_tolerance:
                        print(f"Motif {mname} constructed with sequence candidate set {candidate_set} has Tm {Tm} which is out of bounds. Forbidding...")
                        continue
                    found_any_candidate_set = True
                    # to keep things easy here, don't use reverse-compliment names
                    # we're using the motif name as a dict key, so we do know which is which
                    motif_fulfillment_options[mname].add(frozenset(
                        zip([name_rc(dn) if is_rc(dn) else dn for dn in motif if "_" not in dn], candidate_set)
                    ))
                    for dn, seq in zip([dn for dn in motif if "_" not in dn], candidate_set):
                        if is_rc(dn):
                            dn = name_rc(dn)
                        usable_domain_candidates[dn].add(seq)

            # if - for some motif - no valid candidate set was found, that means that we aren't searching
            # a large enouch set of canididate sequences for our domains
            if not found_any_candidate_set:
                return False # outer loop will widen search by enlarging pool

        # check if we have enough post-screen candidates
        for (seq_len, gc_count), request_count in self.__c_request_counts.items():
            request_set = set()
            for domain_name, (domain_seq_len, domain_gc_count) in self.requested_domains.items():
                if seq_len == domain_seq_len and domain_gc_count == gc_count:
                    request_set.update(usable_domain_candidates[domain_name])
            if len(request_set) < request_count: # if we have not found enough sequences for this (seq, gc) pair...
                return False


        return True

    def relative_request_count(self, dlen: int, dgc: int, pool_size_relative: float) -> int:
        return max(2, ceil(self.__c_request_counts[(dlen, dgc)] * pool_size_relative))

    def __request_domain_seq_candidates(self, pool_size_relative: float):
        """
        requests - as needed - additional candidate sequences, until we've arrived at the number we need for
        each (dlen, dgc) domain count
        """
        # loop unique (dlen, dgc) pairs and the number of domains with (dlen, dgc)
        for (dlen, dgc), count in self.__c_request_counts.items():
            # generate using a while loop rather than list processing, since we have to reject some sequences
            # minimum sequence requests should be 2 so we always have *some* options
            while len(self.__c_candidates[(dlen, dgc)]) < self.relative_request_count(dlen, dgc, pool_size_relative):
                seq = self.generate_sequence(dlen, dgc)
                # reject sequences with the wrong counts of successive bases,
                # or is a reverse compliment of an existing sequence
                if check_seq_valid(seq) and rc(seq) not in self.__c_candidates[(dlen, dgc)]:
                    self.__c_candidates[(dlen, dgc)].add(seq)

    def __find_strand_dgs(self, domain_assignments: dict[str, str]) -> pd.DataFrame:
        """
        computes the delta-Gs for every strand pairing
        todo: do we need to optimize memory for large numbers of domains?
        Parameters:
            domain_assignments a map of domain names to seqences
        returns: a mapping of each strand pair to a delta-G

        todo: cache
        """
        strand_sequences: list[str] = [
            "".join([domain_assignments[domain] for domain in strand])
            for strand in self.motifs.values()
        ]
        # spacers are implicitly inclued. todo: constraint_seqs
        return compute_dGs(strand_sequences, self.model, self.filter_struct)

    def __iter_domain_assigments(self) -> Generator[dict[str, str], None, None]:
        """

        """
        pass

    def generate_sequence(self, length: int, gc_count: int) -> str:
        """
        generate sequences with requested length and gc count
        todo: -1 should produce sequence of variable gc count
        raises GeneratorExit if it runs out of sequences
        """
        assert -1 < gc_count < length
        # if we don't already have a method to generate sequences for this
        if (length, gc_count) not in self.seq_generators_by_len_gc:
            self.seq_generators_by_len_gc[(length, gc_count)] = generate_unique_sequence(length, gc_count)
        # generate sequence from
        seq = next(self.seq_generators_by_len_gc[(length, gc_count)])
        return seq

    def reset_seq_generator(self, length: int, gc_count: int):
        """
        resets the sequence generator for sequences of given length and gc count
        """
        self.seq_generators_by_len_gc[(length, gc_count)] = generate_unique_sequence(length, gc_count)

    def reset_all_seq_generators(self):
        """
        reset all sequence generators
        """
        for length, gc_count in self.seq_generators_by_len_gc:
            self.reset_seq_generator(length, gc_count)

    def screen_tms(self, seqs: list[str]) -> dict[str, float]:
        """
        screens sequences
        shadows method `melting_temp_screen` from `create_same_tm_seq_library.py`
        """
        if self.mt_algo in['both', 'biopy']:
            biopy_final_candidate = {}
            for seq in seqs:
                # todo: make Tm_NN params included in class properties?
                bio_temp = Bio.SeqUtils.MeltingTemp.Tm_NN(seq,
                                                          dnac1=10,
                                                          dnac2=10,
                                                          Na=50, # in mM (?)
                                                          K=0,
                                                          Tris=0,
                                                          Mg=12.5, # in mM (?)
                                                          dNTPs=0,
                                                          saltcorr=7)
                if (bio_temp > self.temperature - self.temperature_tolerance) and (bio_temp < self.temperature + self.temperature_tolerance):
                    biopy_final_candidate[seq] = bio_temp

            if self.mt_algo == 'biopy':
                return biopy_final_candidate

            bioseqs = list(biopy_final_candidate.keys())

            final_candidate = self.screen_tms_nupack(bioseqs)

            return final_candidate
        # TODO: it looks like the 'nupack' and 'biopy' code is identical here?
        elif self.mt_algo == 'nupack':
            final_candidate = self.screen_tms_nupack(seqs)
        else:
            raise Exception(f"Unknown MT algorithm {self.mt_algo}")

        return final_candidate

    def get_tm_seq(self, seq: str) -> float:
        if self.mt_algo == 'nupack':
            return self.screen_tms_nupack([seq])[seq]
        else:
            # for "both" use "biopy"
            return Bio.SeqUtils.MeltingTemp.Tm_NN(seq,
                                                      dnac1=10,
                                                      dnac2=10,
                                                      Na=50,  # in mM
                                                      K=0,
                                                      Tris=0,
                                                      Mg=12.5,  # in mM
                                                      dNTPs=0,
                                                      saltcorr=7)

    def screen_tm_seq(self, seq: str) -> float:
        """
        tests if a sequence falls within the desired melting temperature
        """
        if self.mt_algo in ['biopy', "both"]:
            # todo: make Tm_NN params included in class properties?
            bio_temp = Bio.SeqUtils.MeltingTemp.Tm_NN(seq,
                                                      dnac1=10,
                                                      dnac2=10,
                                                      Na=50,  # in mM
                                                      K=0,
                                                      Tris=0,
                                                      Mg=12.5,  # in mM
                                                      dNTPs=0,
                                                      saltcorr=7)
            if self.mt_algo == 'biopy':
                if (self.temperature - self.temperature_tolerance) < bio_temp < (self.temperature + self.temperature_tolerance):
                    final_candidate = bio_temp
                else:
                    final_candidate = -1
            else:
                assert self.mt_algo == 'both'
                # this probably doesn't work
                final_candidate = self.screen_tms_nupack([seq])[seq] # i could rewrite this function but won't
                if (self.temperature - self.temperature_tolerance) < final_candidate < (self.temperature + self.temperature_tolerance):
                    final_candidate = bio_temp
                else:
                    final_candidate = -1
        else:
            assert self.mt_algo == 'nupack'
            final_candidate = self.screen_tms_nupack([seq])[seq]
            if not (self.temperature - self.temperature_tolerance) < final_candidate < (self.temperature + self.temperature_tolerance):
                final_candidate = -1

        return final_candidate

    def screen_tms_nupack(self, bioseqs: list[str]) -> dict[str, float]:
        """
        todo: i'm like 90% sure this method is broken
        """
        unbound_fraction = get_unbound_fraction(bioseqs, self.temperature)
        temp_correct_seqs = {}
        for seq, frac in zip(bioseqs, unbound_fraction):
            value = frac
            if (value > 0.45) and (value < 0.55):
                temp_correct_seqs[seq] = value
        all_seqs = list(temp_correct_seqs.keys())
        melting_temperatures, unbound_fractions = self.compute_melting_temp(all_seqs)
        final_candidate = {}
        for seq, tp in melting_temperatures.items():
            if (tp > self.temperature - self.temperature_tolerance) and (
                    tp < self.temperature + self.temperature_tolerance):
                final_candidate[seq] = tp
        return final_candidate

    def get_temp_range(self)->np.ndarray:
        temp_window = self.temperature_tolerance * 5
        return np.linspace(self.temperature - temp_window, self.temperature + temp_window, 21)

    def compute_melting_temp(self, all_seqs: list[str]) -> tuple[dict[str, list[float]],
                                                                 dict[str, list[float]]]:
        """
        shadows `compute_melting_temp` from `create_same_tm_seq_library.py`
        computes melting temperatures for the provided sequence
        """
        unbound_fractions = {seq: [] for seq in all_seqs}
        # compute unbound fractions for sequences
        for temp in self.get_temp_range():
            seq_wise_fractions = get_unbound_fraction(all_seqs, temp)
            for seq, frac in zip(all_seqs, seq_wise_fractions):
                unbound_fractions[seq].append(frac)

        # compute unbound fractions for sequences
        melting_temperatures = {}
        for seq, all_fracs in unbound_fractions.items():
            melt = self.get_temp_range()[np.abs(np.array(all_fracs) - 0.5).argmin()]
            melting_temperatures[seq] = melt

        return melting_temperatures, unbound_fractions

    def set_polyT(self, polyT_length: int, polyT_identifier: str = "_"):
        """
        sets the "default" polyT length
        by convention, the "default" poly-T is designated as domain "_" and further poly-Ts are
        designated by more underscores
        """
        self.domains[polyT_identifier] = "T" * polyT_length

    def get_sequences(self) -> list[str]:
        """
        returns DNA sequences for requested motifs
        """
        sequences = []
        for motif in self.motifs:
            seq = ""
            for domain in motif:
                if domain not in self.domains:
                    raise Exception(f"Domain {domain} has not been assigned a sequence!")
                seq += self.domains[domain]
            sequences.append(seq)
        return sequences

    def check_orthogonality(self):
        sequences = self.get_sequences()
